### ISSUE TITLE
Training Params

### ISSUE THREAD

**Issue by imaccormick275** [codeniko/shape_predictor_81_face_landmarks#12]
Hi Niko,

Could I trouble you for the training params you used to train your dlib model. 

I'm trying to train a model on Helen at the moment and then will try on my custom forehead points (iBUG) further down the line. 

I feel like I picked reasonable params according to documentation and articles out there but my train/test errors were well off. Would be very helpful for me to sense check. 

Iain

**Comment by codeniko** [comment]
I did not keep those, sorry
