### ISSUE TITLE
how do i get addition 13 landmarks

### ISSUE THREAD

**Issue by GeneralJing** [codeniko/shape_predictor_81_face_landmarks#14]
training datasets only 68 landmarks, How to get the other 13 key points？Can you explain it more specificly?

**Comment by codeniko** [comment]
Sure, I've already answered this in more detail in https://github.com/codeniko/shape_predictor_81_face_landmarks/issues/6

https://github.com/codeniko/shape_predictor_81_face_landmarks/issues/11 can also be helpful with further insights
