### ISSUE TITLE
81 face landmarks with Caffe DNN

### ISSUE THREAD

**Issue by chezhung** [codeniko/shape_predictor_81_face_landmarks#16]
Hi sorry if this is abrupt.

First of all, thank you so much for the excellent work! Your trained data set really helped me so much!

But I'm wondering if it's possible that you could maybe share your source data so I can try to train it with Caffe DNN since it doesn't work well with Caffe DNN face detection.

I'll definitely share the trained model if I could train it successfully.
Thank you.

**Comment by codeniko** [comment]
The data I used was the ibug dataset of faces. It comes with 68 landmark coords. You can then see #6 and #11 to see how I got the next 13 landmarks which I appended to to original 68 landmark coords
