### ISSUE TITLE
creating a new predictor

### ISSUE THREAD

**Issue by UrstrulyRoot** [codeniko/shape_predictor_81_face_landmarks#3]
Hi, I want to create a predictor that just outputs 12 landmarks corresponding to eyes instead of all 68.How should my training xml file reflect to serve my purpose?
can i achieve it by only having 12 co-ordinates in the xml file?
Thanks in advance

**Comment by codeniko** [comment]
I only recently saw this, sorry. I hope you've figured this out but it's as you said. You can download ibug images and remove the coordinates you're not interested in, keeping only the ones around the eyes. Retrain by using http://dlib.net/train_shape_predictor.py.html
