### ISSUE TITLE
An error appeared when running the demo

### ISSUE THREAD

**Issue by githubcyy** [codeniko/shape_predictor_81_face_landmarks#5]
RuntimeError: Error deserializing object of type int
![image](https://user-images.githubusercontent.com/40297314/54528203-35aec600-49b7-11e9-864c-79063d94456d.png)

**Comment by codeniko** [comment]
May I ask what python version you are using? I'm not sure how it's done on windows, but on linux/mac you can run `python --version` in terminal

**Comment by imaccormick275** [comment]
Hi codeniko, I have had the same problem. I am currently running python 3.6.5

Thanks for training this model, the forehead landmarks would be really useful to me. 

Out of interest, how did you create your training landmarks for the forehead region? Is there a publicly available dataset out there or did you do the landmarking yourself?

**Comment by imaccormick275** [comment]
I had the same problem but managed to resolve. I was reading somewhere the error can happen if the file is corrupted. So I git cloned the entire repository to get the file rather than downloading the individual file manually. I have no idea why this would make any difference but it seems to have fixed the issue.

**Comment by imaccormick275** [comment]
If you have a spare moment would be still interested in knowing the answer to my question above:

"Out of interest, how did you create your training landmarks for the forehead region? Is there a publicly available dataset out there or did you do the landmarking yourself?"

**Comment by codeniko** [comment]
Awesome! Not sure why that's the case but happy that it worked
